all: eq2doGrado01 eq2doGrado02

eq2doGrado01: eq2doGrado01.c
	gcc -Wall -o eq2doGrado01 eq2doGrado01.c -lm

eq2doGrado02: eq2doGrado02.cpp
	g++ -Wall -o eq2doGrado02 eq2doGrado02.cpp

clean:
	rm eq2doGrado01 eq2doGrado02