all: ejApuntadores1  ejApuntadores2  ejArreglos

ejApuntadores1: ejApuntadores1.cpp
	g++ -Wall -o ejApuntadores1 ejApuntadores1.cpp

ejApuntadores2: ejApuntadores2.cpp
	g++ -Wall -o ejApuntadores2 ejApuntadores2.cpp

ejArreglos: ejArreglos.cpp
	g++ -Wall -o ejArreglos ejArreglos.cpp

clean:
	rm ejApuntadores1  ejApuntadores2  ejArreglos