all: pruebaArrInt01 pruebaArrInt02

pruebaArrInt01: pruebaArrInt01.cpp
	g++ -Wall -g -o pruebaArrInt01 pruebaArrInt01.cpp

pruebaArrInt02: pruebaArrInt02.cpp arrInt.h
	g++ -Wall -g -o pruebaArrInt02 pruebaArrInt02.cpp

clean:
	rm pruebaArrInt01 pruebaArrInt02
