all: pruebaArrInt01 pruebaArrInt02 pruebaArreglo01 pruebaArreglo02

pruebaArrInt01: pruebaArrInt01.cpp
	g++ -Wall -g -o pruebaArrInt01 pruebaArrInt01.cpp

pruebaArrInt02: pruebaArrInt02.cpp arrInt.h
	g++ -Wall -g -o pruebaArrInt02 pruebaArrInt02.cpp

pruebaArreglo01: pruebaArreglo01.cpp arreglo.h
	g++ -Wall -g -o pruebaArreglo01 pruebaArreglo01.cpp

pruebaArreglo02: pruebaArreglo02.cpp arreglo.h
	g++ -Wall -g -o pruebaArreglo02 pruebaArreglo02.cpp


clean:
	rm pruebaArrInt01 pruebaArrInt02 pruebaArreglo01 pruebaArreglo02
